/** @file notification.c 
*   @brief User Notification Definition File
*   @date 9.Sep.2014
*   @version 04.01.00
*
*   This file  defines  empty  notification  routines to avoid
*   linker errors, Driver expects user to define the notification. 
*   The user needs to either remove this file and use their custom 
*   notification function or place their code sequence in this file 
*   between the provided USER CODE BEGIN and USER CODE END.
*
*/

/* Include Files */

#include "esm.h"
#include "sys_selftest.h"
#include "gio.h"
#include "rti.h"

/* USER CODE BEGIN (0) */
#include "TMS_scanner_synch.h"
/* USER CODE END */

#pragma WEAK(esmGroup1Notification)
void esmGroup1Notification(uint32 channel)
{
/*  enter user code between the USER CODE BEGIN and USER CODE END. */
/* USER CODE BEGIN (1) */
/* USER CODE END */
}

/* USER CODE BEGIN (2) */
/* USER CODE END */
#pragma WEAK(esmGroup2Notification)
void esmGroup2Notification(uint32 channel)
{
/*  enter user code between the USER CODE BEGIN and USER CODE END. */
/* USER CODE BEGIN (3) */
/* USER CODE END */
}

/* USER CODE BEGIN (4) */
/* USER CODE END */
#pragma WEAK(memoryPort0TestFailNotification)
void memoryPort0TestFailNotification(uint32 groupSelect, uint32 dataSelect, uint32 address, uint32 data)
{
/*  enter user code between the USER CODE BEGIN and USER CODE END. */
/* USER CODE BEGIN (5) */
/* USER CODE END */
}

/* USER CODE BEGIN (6) */
/* USER CODE END */
#pragma WEAK(memoryPort1TestFailNotification)
void memoryPort1TestFailNotification(uint32 groupSelect, uint32 dataSelect, uint32 address, uint32 data)
{
/*  enter user code between the USER CODE BEGIN and USER CODE END. */
/* USER CODE BEGIN (7) */
/* USER CODE END */
}

/* USER CODE BEGIN (8) */
/* USER CODE END */
#pragma WEAK(rtiNotification)
void rtiNotification(uint32 notification)
{
/*  enter user code between the USER CODE BEGIN and USER CODE END. */
/* USER CODE BEGIN (9) */
/* USER CODE END */
}


/* USER CODE BEGIN (10) */

/* gioNotification() is the interrupt service routine (ISR) for the hardware interrupt generated by the 10 us pulse from
 * the MRI scanner. The hardware interrupt occurs when pin A7 of GIO PORTA detects the leading edge of the 10 us pulse
 * from the MRI scanner. The trig_count variable is incremented in the RTI hardware interrupt ISR.*/

extern unsigned int irq_count;
extern unsigned int train_count;
extern unsigned TMS_trig_in_progress;
extern TMS_struct TMS[];
/* USER CODE END */

#pragma WEAK(gioNotification)
void gioNotification(gioPORT_t *port, uint32 bit)
{
/*  enter user code between the USER CODE BEGIN and USER CODE END. */
/* USER CODE BEGIN (19) */

	// The irq_count is initialized to zero in sys_main.c.
	irq_count = irq_count + 1;

	if((irq_count == TMS[train_count].trig_image_vol) && (TMS_trig_in_progress == 0)){

		// Schedule the leading edge of the first trigger pulse (of a train) to the TMS unit.
		rtiREG1->CMP[0U].COMPx = rtiREG1->CNT[0U].CAFRCx + TMS[train_count].trig_time[0];

	}

	// This toggles the Hercules D12 LED to indicate that an IRQ occurred for trouble shooting purposes.
	gioToggleBit(gioPORTA, 2);

/* USER CODE END */
}

/* USER CODE BEGIN (20) */
/* USER CODE END */




/* USER CODE BEGIN (43) */
/* USER CODE END */


/* USER CODE BEGIN (47) */
/* USER CODE END */


/* USER CODE BEGIN (50) */
/* USER CODE END */


/* USER CODE BEGIN (53) */
/* USER CODE END */


/* USER CODE BEGIN (56) */
/* USER CODE END */

/* USER CODE BEGIN (58) */
/* USER CODE END */

/* USER CODE BEGIN (60) */
/* USER CODE END */
